# Generated by Django 5.1.2 on 2024-10-31 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_lancamento', models.DateField()),
                ('numero_de_faixas', models.IntegerField()),
                ('capa', models.URLField(blank=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.artista')),
            ],
        ),
    ]
