# Generated by Django 5.1.3 on 2024-11-08 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao_execucao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.CharField(max_length=255)),
                ('data_fim', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('exercicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.exercicios')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='artista',
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
